/**
 * Pronunciation service — wraps Tauri IPC for pinyin/furigana/romaji/bopomofo
 * annotation with an in-memory cache.
 *
 * All public methods are synchronous for cache reads; the Tauri invoke is
 * async and only fires on cache miss.
 */

import type { Pronunciation, PronunciationMode } from "../types/lyrics";

// ---------------------------------------------------------------------------
// Types shared between Rust backend and frontend
// ---------------------------------------------------------------------------

export interface PronunciationResult {
  text: string;
  pinyin: string;
  tone: number;
  alternatives: string[];
}

export interface CharLookupInput {
  text: string;
  context: string | null;
}

export interface AnnotatedCharResult {
  text: string;
  pronunciation: PronunciationResult | null;
}

// ---------------------------------------------------------------------------
// Cache
// ---------------------------------------------------------------------------

const cache = new Map<string, Pronunciation | null>();

function cacheKey(text: string, mode: string): string {
  return `${mode}::${text}`;
}

// ---------------------------------------------------------------------------
// Helpers — convert between type systems
// ---------------------------------------------------------------------------

/** Convert a Rust PronunciationResult to the frontend Pronunciation type. */
function toPronunciation(
  r: PronunciationResult,
  mode: PronunciationMode,
  isAutoGenerated: boolean,
): Pronunciation {
  return {
    mode,
    text: r.pinyin,
    tone: r.tone,
    isAutoGenerated,
    alternatives: r.alternatives.length > 0 ? r.alternatives : undefined,
  };
}

// ---------------------------------------------------------------------------
// Tauri invoke (lazy — avoids bundling issues if Tauri is not available)
// ---------------------------------------------------------------------------

import type { invoke as InvokeFn } from "@tauri-apps/api/core";

let _invoke: typeof InvokeFn | null = null;

async function getInvoke(): Promise<typeof InvokeFn> {
  if (!_invoke) {
    _invoke = (await import("@tauri-apps/api/core")).invoke;
  }
  return _invoke;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Look up pronunciation of a single character.
 *
 * Returns `null` when the character is not in the dictionary (e.g.
 * punctuation, spaces, or unknown characters).
 */
export async function lookup(
  text: string,
  mode: PronunciationMode,
): Promise<Pronunciation | null> {
  if (mode === "none" || !text.trim()) return null;

  const key = cacheKey(text, mode);
  const cached = cache.get(key);
  if (cached !== undefined) return cached;

  try {
    const invoke = await getInvoke();
    const result: PronunciationResult | null = await invoke(
      "pronunciation_lookup",
      { text, mode },
    );

    const pronunciation = result
      ? toPronunciation(result, mode, true)
      : null;

    cache.set(key, pronunciation);
    return pronunciation;
  } catch (err) {
    console.warn("[PronunciationService] lookup failed:", err);
    cache.set(key, null);
    return null;
  }
}

/**
 * Annotate all non-whitespace characters in the given lines.
 *
 * Characters that already have a `pronunciation` set are left untouched
 * (preserving manual edits).  Returns the updated lines array.
 */
export async function annotateAll(
  lines: Array<{
    characters: Array<{
      id: string;
      text: string;
      isPunctuation: boolean;
      isSpace: boolean;
      pronunciation?: Pronunciation | null;
    }>;
  }>,
  mode: PronunciationMode,
): Promise<void> {
  if (mode === "none") return;

  // Collect characters that need lookup
  const lookupIndices: Array<{ lineIdx: number; charIdx: number; text: string }> = [];
  const batchTexts: string[] = [];

  for (let li = 0; li < lines.length; li++) {
    const chars = lines[li].characters;
    for (let ci = 0; ci < chars.length; ci++) {
      const ch = chars[ci];
      if (
        ch.text.trim() &&
        !ch.isPunctuation &&
        !ch.isSpace &&
        !ch.pronunciation
      ) {
        const key = cacheKey(ch.text, mode);
        if (cache.has(key)) {
          // Already cached — skip batch for this one
          continue;
        }
        lookupIndices.push({ lineIdx: li, charIdx: ci, text: ch.text });
        batchTexts.push(ch.text);
      }
    }
  }

  if (lookupIndices.length === 0) return;

  try {
    const invoke = await getInvoke();
    const inputs: CharLookupInput[] = lookupIndices.map((li) => ({
      text: li.text,
      context: null,
    }));

    const results: AnnotatedCharResult[] = await invoke(
      "pronunciation_annotate_batch",
      { chars: inputs, mode },
    );

    // Update cache and return mapped result positions
    const updates: Array<{
      id: string;
      pronunciation: Pronunciation | null;
    }> = [];

    for (let i = 0; i < results.length; i++) {
      const r = results[i];
      const idx = lookupIndices[i];

      const pronunciation = r.pronunciation
        ? toPronunciation(r.pronunciation, mode, true)
        : null;

      const key = cacheKey(idx.text, mode);
      cache.set(key, pronunciation);

      updates.push({
        id: lines[idx.lineIdx].characters[idx.charIdx].id,
        pronunciation,
      });
    }

    // Apply updates via the store (importing here avoids circular deps at module level)
    const { useStore } = await import("../store");
    for (const u of updates) {
      if (u.pronunciation) {
        useStore.getState().updateCharPronunciation(u.id, u.pronunciation);
      }
    }
  } catch (err) {
    console.warn("[PronunciationService] batch annotate failed:", err);
  }
}

/**
 * Annotate a specific set of characters (from selected lines or manual selection).
 */
export async function annotateChars(
  chars: Array<{
    id: string;
    text: string;
  }>,
  mode: PronunciationMode,
): Promise<void> {
  if (mode === "none" || chars.length === 0) return;

  try {
    const invoke = await getInvoke();
    const inputs: CharLookupInput[] = chars.map((c) => ({
      text: c.text,
      context: null,
    }));

    const results: AnnotatedCharResult[] = await invoke(
      "pronunciation_annotate_batch",
      { chars: inputs, mode },
    );

    const { useStore } = await import("../store");
    for (let i = 0; i < results.length; i++) {
      const r = results[i];
      const pronunciation = r.pronunciation
        ? toPronunciation(r.pronunciation, mode, true)
        : null;

      cache.set(cacheKey(chars[i].text, mode), pronunciation);

      if (pronunciation) {
        useStore.getState().updateCharPronunciation(chars[i].id, pronunciation);
      }
    }
  } catch (err) {
    console.warn("[PronunciationService] annotateChars failed:", err);
  }
}

/** Clear the in-memory pronunciation cache. */
export function clearCache(): void {
  cache.clear();
}
