import { useState, useCallback } from "react";
import { useTranslation } from "react-i18next";
import { useStore } from "../../store";
import * as pronunciationService from "../../services/pronunciationService";
import type { PronunciationMode, Pronunciation } from "../../types/lyrics";

const MODES: PronunciationMode[] = [
  "none",
  "pinyin",
  "furigana",
  "romaji",
  "bopomofo",
];

interface EditingChar {
  lineIdx: number;
  charIdx: number;
  charId: string;
  text: string;
  currentPronunciation: Pronunciation | null | undefined;
}

/**
 * PronunciationPanel — batch annotation, manual editing, mode switching.
 *
 * Reads lines and pronunciation mode from the Zustand store.
 */
export function PronunciationPanel() {
  const { t } = useTranslation();
  const lines = useStore((s) => s.lines);
  const pronunciationMode = useStore((s) => s.pronunciationMode) as PronunciationMode;
  const updateCharPronunciation = useStore((s) => s.updateCharPronunciation);
  const setPronunciationMode = useStore((s) => s.setPronunciationMode);

  const [isAnnotating, setIsAnnotating] = useState(false);
  const [editingChar, setEditingChar] = useState<EditingChar | null>(null);
  const [editValue, setEditValue] = useState("");
  const [showAlternatives, setShowAlternatives] = useState<string | null>(null);

  // Count how many characters have pronunciation data
  const annotatedCount = lines.reduce(
    (sum, line) =>
      sum + line.characters.filter((c) => c.pronunciation != null).length,
    0,
  );

  const totalChars = lines.reduce(
    (sum, line) => sum + line.characters.length,
    0,
  );

  // ---- Handlers ----

  const handleModeChange = useCallback(
    (mode: PronunciationMode) => {
      setPronunciationMode(mode);
    },
    [setPronunciationMode],
  );

  const handleAnnotateAll = useCallback(async () => {
    if (pronunciationMode === "none" || lines.length === 0) return;
    setIsAnnotating(true);
    try {
      await pronunciationService.annotateAll(lines, pronunciationMode);
    } finally {
      setIsAnnotating(false);
    }
  }, [lines, pronunciationMode]);

  const handleAnnotateSelected = useCallback(async () => {
    const selectedIdx = useStore.getState().selectedLineIndex;
    if (selectedIdx === null || pronunciationMode === "none") return;
    setIsAnnotating(true);
    try {
      const selectedLine = lines[selectedIdx];
      if (!selectedLine) return;
      await pronunciationService.annotateAll(
        [selectedLine],
        pronunciationMode,
      );
    } finally {
      setIsAnnotating(false);
    }
  }, [lines, pronunciationMode]);

  const handleClearAll = useCallback(() => {
    for (const line of lines) {
      for (const ch of line.characters) {
        if (ch.pronunciation) {
          updateCharPronunciation(ch.id, null as unknown as Pronunciation);
        }
      }
    }
  }, [lines, updateCharPronunciation]);

  const handleClearCache = useCallback(() => {
    pronunciationService.clearCache();
  }, []);

  // Open manual edit popup for a character
  const handleCharClick = useCallback(
    (editing: EditingChar) => {
      setEditingChar(editing);
      setEditValue(editing.currentPronunciation?.text ?? "");
      setShowAlternatives(null);
    },
    [],
  );

  // Save manual edit
  const handleSaveEdit = useCallback(() => {
    if (!editingChar) return;
    const trimmed = editValue.trim();
    if (trimmed) {
      const pronunciation: Pronunciation = {
        mode: pronunciationMode,
        text: trimmed,
        isAutoGenerated: false,
      };
      updateCharPronunciation(editingChar.charId, pronunciation);
    }
    setEditingChar(null);
    setEditValue("");
  }, [editingChar, editValue, pronunciationMode, updateCharPronunciation]);

  // Select alternative pronunciation
  const handleSelectAlternative = useCallback(
    (alt: string) => {
      if (!editingChar) return;
      setEditValue(alt);
      setShowAlternatives(null);
    },
    [editingChar],
  );

  // Cancel manual edit
  const handleCancelEdit = useCallback(() => {
    setEditingChar(null);
    setEditValue("");
    setShowAlternatives(null);
  }, []);

  // Keyboard handler for edit input
  const handleEditKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === "Enter") {
        handleSaveEdit();
      } else if (e.key === "Escape") {
        handleCancelEdit();
      }
    },
    [handleSaveEdit, handleCancelEdit],
  );

  // ---- Render ----

  return (
    <div className="flex flex-col gap-3 p-3 bg-gray-900 rounded-lg text-sm select-none">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h3 className="text-xs font-semibold uppercase tracking-wider text-gray-400">
          {t("pronunciation.panel")}
        </h3>
        <span className="text-xs text-gray-500">
          {annotatedCount}/{totalChars}
        </span>
      </div>

      {/* Mode selector */}
      <div className="flex flex-wrap gap-1">
        {MODES.map((mode) => (
          <button
            key={mode}
            onClick={() => handleModeChange(mode)}
            className={`px-2 py-1 text-xs rounded transition-colors ${
              pronunciationMode === mode
                ? "bg-blue-600 text-white"
                : "bg-gray-700 text-gray-300 hover:bg-gray-600"
            }`}
          >
            {t(`pronunciation.${mode}`)}
          </button>
        ))}
      </div>

      {/* Action buttons */}
      <div className="flex flex-wrap gap-1.5">
        <button
          onClick={handleAnnotateAll}
          disabled={isAnnotating || pronunciationMode === "none"}
          className={`px-3 py-1.5 text-xs rounded font-medium transition-colors ${
            isAnnotating || pronunciationMode === "none"
              ? "bg-gray-700 text-gray-500 cursor-not-allowed"
              : "bg-green-700 text-white hover:bg-green-600"
          }`}
        >
          {isAnnotating ? t("common.loading") : t("pronunciation.annotateAll")}
        </button>

        <button
          onClick={handleAnnotateSelected}
          disabled={isAnnotating || pronunciationMode === "none"}
          className={`px-3 py-1.5 text-xs rounded font-medium transition-colors ${
            isAnnotating || pronunciationMode === "none"
              ? "bg-gray-700 text-gray-500 cursor-not-allowed"
              : "bg-green-800 text-white hover:bg-green-700"
          }`}
        >
          {t("pronunciation.annotateSelected")}
        </button>

        <button
          onClick={handleClearAll}
          disabled={annotatedCount === 0}
          className={`px-3 py-1.5 text-xs rounded font-medium transition-colors ${
            annotatedCount === 0
              ? "bg-gray-700 text-gray-500 cursor-not-allowed"
              : "bg-red-800 text-white hover:bg-red-700"
          }`}
        >
          {t("pronunciation.clearAll")}
        </button>

        <button
          onClick={handleClearCache}
          className="px-3 py-1.5 text-xs rounded font-medium bg-gray-700 text-gray-300 hover:bg-gray-600 transition-colors"
        >
          {t("pronunciation.clearAll")}
        </button>
      </div>

      {/* Character-by-character annotations */}
      <div className="max-h-48 overflow-y-auto border border-gray-700 rounded p-2 space-y-1">
        {lines.length === 0 && (
          <p className="text-xs text-gray-500 text-center py-2">
            {t("media.noMedia")}
          </p>
        )}
        {lines.map((line, li) => (
          <div key={line.id} className="flex flex-wrap gap-0.5">
            {line.characters.map((ch, ci) => {
              const hasPron = ch.pronunciation != null;
              return (
                <button
                  key={ch.id}
                  onClick={() =>
                    handleCharClick({
                      lineIdx: li,
                      charIdx: ci,
                      charId: ch.id,
                      text: ch.text,
                      currentPronunciation: ch.pronunciation,
                    })
                  }
                  className={`relative flex flex-col items-center px-1 py-0.5 rounded text-xs transition-colors ${
                    hasPron
                      ? "bg-blue-900/40 hover:bg-blue-800/60"
                      : "hover:bg-gray-700"
                  }`}
                >
                  <span className="text-[10px] leading-tight text-blue-300">
                    {ch.pronunciation?.text ?? " "}
                  </span>
                  <span className="text-xs leading-tight text-white">
                    {ch.text}
                  </span>
                </button>
              );
            })}
          </div>
        ))}
      </div>

      {/* Manual edit popup */}
      {editingChar && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <div className="bg-gray-800 rounded-lg p-4 shadow-xl w-72 border border-gray-600">
            <h4 className="text-sm font-semibold mb-3 text-white">
              {t("pronunciation.editPronunciation")}:{" "}
              <span className="text-lg">{editingChar.text}</span>
            </h4>

            <input
              type="text"
              value={editValue}
              onChange={(e) => setEditValue(e.target.value)}
              onKeyDown={handleEditKeyDown}
              placeholder={t("pronunciation.pinyin")}
              className="w-full px-3 py-2 text-sm bg-gray-700 border border-gray-600 rounded text-white placeholder-gray-400 focus:outline-none focus:border-blue-500 mb-2"
              autoFocus
            />

            {/* Alternatives from dictionary */}
            {editingChar.currentPronunciation?.alternatives &&
              editingChar.currentPronunciation.alternatives.length > 0 && (
                <div className="mb-2">
                  <button
                    onClick={() =>
                      setShowAlternatives(
                        showAlternatives === editingChar.charId
                          ? null
                          : editingChar.charId,
                      )
                    }
                    className="text-xs text-blue-400 hover:text-blue-300"
                  >
                    {showAlternatives === editingChar.charId
                      ? t("common.close")
                      : `${t("common.confirm")} (${editingChar.currentPronunciation.alternatives.length})`}
                  </button>

                  {showAlternatives === editingChar.charId && (
                    <div className="mt-1 flex flex-wrap gap-1">
                      {editingChar.currentPronunciation.alternatives.map(
                        (alt, i) => (
                          <button
                            key={i}
                            onClick={() => handleSelectAlternative(alt)}
                            className="px-2 py-0.5 text-xs bg-gray-700 text-gray-200 rounded hover:bg-gray-600"
                          >
                            {alt}
                          </button>
                        ),
                      )}
                    </div>
                  )}
                </div>
              )}

            <div className="flex gap-2 justify-end">
              <button
                onClick={handleCancelEdit}
                className="px-3 py-1.5 text-xs bg-gray-700 text-gray-300 rounded hover:bg-gray-600"
              >
                {t("common.cancel")}
              </button>
              <button
                onClick={handleSaveEdit}
                className="px-3 py-1.5 text-xs bg-blue-700 text-white rounded hover:bg-blue-600"
              >
                {t("common.save")}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
