export type PronunciationMode =
  | "none"
  | "pinyin"
  | "furigana"
  | "romaji"
  | "bopomofo"
  | "custom";

export interface Pronunciation {
  mode: PronunciationMode;
  text: string;
  tone?: number;
  isAutoGenerated: boolean;
  alternatives?: string[];
}

export interface StyleOverride {
  unsungColor?: string;
  sungColor?: string;
}

export interface LyricChar {
  id: string;
  lineId: string;
  index: number;
  text: string;
  startTime: number;
  endTime: number;
  isPunctuation: boolean;
  isSpace: boolean;
  easing?: string;
  pronunciation?: Pronunciation;
  styleOverride?: StyleOverride;
}

export interface LyricLine {
  id: string;
  index: number;
  text: string;
  characters: LyricChar[];
  startTime: number;
  endTime: number;
  isSkipped: boolean;
  tag?: string;
  styleOverride?: StyleOverride;
  pronunciationMode?: PronunciationMode;
}

/** Raw parsed line data before character-level resolution */
export interface LyricLineData {
  text: string;
  startTime?: number;
  endTime?: number;
}

export interface ParsedLyrics {
  format: "plain" | "lrc" | "srt" | "ass";
  metadata: Record<string, string>;
  lines: LyricLineData[];
}
